// lib/language-support.ts
export const languageOptions = [
  { value: 'javascript', label: 'JavaScript', monaco: 'javascript', prism: 'javascript' },
  { value: 'typescript', label: 'TypeScript', monaco: 'typescript', prism: 'typescript' },
  { value: 'tsx', label: 'TSX (React)', monaco: 'typescript', prism: 'tsx' },
  { value: 'python', label: 'Python', monaco: 'python', prism: 'python' },
  { value: 'java', label: 'Java', monaco: 'java', prism: 'java' },
  { value: 'html', label: 'HTML', monaco: 'html', prism: 'markup' },
  { value: 'css', label: 'CSS', monaco: 'css', prism: 'css' },
  { value: 'json', label: 'JSON', monaco: 'json', prism: 'json' },
  { value: 'yaml', label: 'YAML', monaco: 'yaml', prism: 'yaml' },
  { value: 'markdown', label: 'Markdown', monaco: 'markdown', prism: 'markdown' },
  { value: 'bash', label: 'Bash/Shell', monaco: 'shell', prism: 'bash' },
  { value: 'sql', label: 'SQL', monaco: 'sql', prism: 'sql' },
  { value: 'go', label: 'Go', monaco: 'go', prism: 'go' },
  { value: 'rust', label: 'Rust', monaco: 'rust', prism: 'rust' },
  { value: 'php', label: 'PHP', monaco: 'php', prism: 'php' },
  { value: 'csharp', label: 'C#', monaco: 'csharp', prism: 'csharp' },
  { value: 'cpp', label: 'C++', monaco: 'cpp', prism: 'cpp' },
  { value: 'c', label: 'C', monaco: 'c', prism: 'c' },
  { value: 'kotlin', label: 'Kotlin', monaco: 'kotlin', prism: 'kotlin' },
  { value: 'swift', label: 'Swift', monaco: 'swift', prism: 'swift' },
  { value: 'ruby', label: 'Ruby', monaco: 'ruby', prism: 'ruby' },
  { value: 'scala', label: 'Scala', monaco: 'scala', prism: 'scala' },
  { value: 'perl', label: 'Perl', monaco: 'perl', prism: 'perl' },
  { value: 'r', label: 'R', monaco: 'r', prism: 'r' },
  { value: 'dart', label: 'Dart', monaco: 'dart', prism: 'dart' },
  { value: 'elixir', label: 'Elixir', monaco: 'elixir', prism: 'elixir' },
  { value: 'erlang', label: 'Erlang', monaco: 'erlang', prism: 'erlang' },
  { value: 'haskell', label: 'Haskell', monaco: 'haskell', prism: 'haskell' },
  { value: 'lua', label: 'Lua', monaco: 'lua', prism: 'lua' },
  { value: 'powershell', label: 'PowerShell', monaco: 'powershell', prism: 'powershell' },
  { value: 'dockerfile', label: 'Dockerfile', monaco: 'dockerfile', prism: 'dockerfile' },
  { value: 'xml', label: 'XML', monaco: 'xml', prism: 'markup' },
  { value: 'graphql', label: 'GraphQL', monaco: 'graphql', prism: 'graphql' },
  { value: 'toml', label: 'TOML', monaco: 'toml', prism: 'toml' },
  { value: 'text', label: '纯文本', monaco: 'plaintext', prism: 'plain' },
  // 额外添加的语言支持
  { value: 'jsx', label: 'JSX (React)', monaco: 'javascript', prism: 'jsx' },
  { value: 'vue', label: 'Vue', monaco: 'html', prism: 'vue' },
  { value: 'svelte', label: 'Svelte', monaco: 'html', prism: 'svelte' },
  { value: 'objective-c', label: 'Objective-C', monaco: 'objective-c', prism: 'objectivec' },
  { value: 'matlab', label: 'MATLAB', monaco: 'matlab', prism: 'matlab' },
  { value: 'vim', label: 'Vim Script', monaco: 'vim', prism: 'vim' },
  { value: 'fortran', label: 'Fortran', monaco: 'fortran', prism: 'fortran' },
  { value: 'clojure', label: 'Clojure', monaco: 'clojure', prism: 'clojure' },
  { value: 'fsharp', label: 'F#', monaco: 'fsharp', prism: 'fsharp' },
  { value: 'scheme', label: 'Scheme', monaco: 'scheme', prism: 'scheme' },
  { value: 'solidity', label: 'Solidity', monaco: 'solidity', prism: 'solidity' },
  { value: 'verilog', label: 'Verilog', monaco: 'verilog', prism: 'verilog' },
  { value: 'coffeescript', label: 'CoffeeScript', monaco: 'coffee', prism: 'coffeescript' },
  { value: 'less', label: 'Less', monaco: 'less', prism: 'less' },
  { value: 'scss', label: 'SCSS', monaco: 'scss', prism: 'scss' },
  { value: 'ini', label: 'INI', monaco: 'ini', prism: 'ini' },
  { value: 'diff', label: 'Diff', monaco: 'diff', prism: 'diff' },
  { value: 'makefile', label: 'Makefile', monaco: 'makefile', prism: 'makefile' },
  { value: 'nim', label: 'Nim', monaco: 'nim', prism: 'nim' },
  { value: 'ocaml', label: 'OCaml', monaco: 'ocaml', prism: 'ocaml' },
  { value: 'pascal', label: 'Pascal', monaco: 'pascal', prism: 'pascal' },
  { value: 'stylus', label: 'Stylus', monaco: 'stylus', prism: 'stylus' },
  { value: 'twig', label: 'Twig', monaco: 'twig', prism: 'twig' },
  { value: 'vb', label: 'Visual Basic', monaco: 'vb', prism: 'vb' },
  { value: 'wasm', label: 'WebAssembly', monaco: 'wasm', prism: 'wast' },
  // 更多现代和特殊用途语言
  { value: 'ada', label: 'Ada', monaco: 'ada', prism: 'ada' },
  { value: 'apex', label: 'Apex', monaco: 'apex', prism: 'apex' },
  { value: 'assembly', label: 'Assembly', monaco: 'assembly', prism: 'armasm' },
  { value: 'autohotkey', label: 'AutoHotkey', monaco: 'autohotkey', prism: 'autohotkey' },
  { value: 'batch', label: 'Batch', monaco: 'batch', prism: 'batch' },
  { value: 'crystal', label: 'Crystal', monaco: 'crystal', prism: 'crystal' },
  { value: 'd', label: 'D', monaco: 'd', prism: 'd' },
  { value: 'elm', label: 'Elm', monaco: 'elm', prism: 'elm' },
  { value: 'factor', label: 'Factor', monaco: 'factor', prism: 'factor' },
  { value: 'fancy', label: 'Fancy', monaco: 'fancy', prism: 'fancy' },
  { value: 'groovy', label: 'Groovy', monaco: 'groovy', prism: 'groovy' },
  { value: 'handlebars', label: 'Handlebars', monaco: 'handlebars', prism: 'handlebars' },
  { value: 'haxe', label: 'Haxe', monaco: 'haxe', prism: 'haxe' },
  { value: 'io', label: 'Io', monaco: 'io', prism: 'io' },
  { value: 'jade', label: 'Jade/Pug', monaco: 'pug', prism: 'pug' },
  { value: 'janet', label: 'Janet', monaco: 'janet', prism: 'janet' },
  { value: 'jsonata', label: 'JSONata', monaco: 'jsonata', prism: 'json' },
  { value: 'julia', label: 'Julia', monaco: 'julia', prism: 'julia' },
  { value: 'livescript', label: 'LiveScript', monaco: 'livescript', prism: 'livescript' },
  { value: 'llvm', label: 'LLVM', monaco: 'llvm', prism: 'llvm' },
  { value: 'mips', label: 'MIPS Assembly', monaco: 'mips', prism: 'mips' },
  { value: 'mojo', label: 'Mojo', monaco: 'mojo', prism: 'python' },
  { value: 'n1ql', label: 'N1QL', monaco: 'n1ql', prism: 'sql' },
  { value: 'nginx', label: 'Nginx Config', monaco: 'nginx', prism: 'nginx' },
  { value: 'nunjucks', label: 'Nunjucks', monaco: 'nunjucks', prism: 'nunjucks' },
  { value: 'pgsql', label: 'PostgreSQL', monaco: 'pgsql', prism: 'pgsql' },
  { value: 'postiats', label: 'Postiats', monaco: 'postiats', prism: 'postiats' },
  { value: 'pug', label: 'Pug', monaco: 'pug', prism: 'pug' },
  { value: 'qml', label: 'QML', monaco: 'qml', prism: 'qml' },
  { value: 'qsharp', label: 'Q#', monaco: 'qsharp', prism: 'qsharp' },
  { value: 'racket', label: 'Racket', monaco: 'racket', prism: 'racket' },
  { value: 'reason', label: 'ReasonML', monaco: 'reason', prism: 'reason' },
  { value: 'roboconf', label: 'Roboconf', monaco: 'roboconf', prism: 'roboconf' },
  { value: 'sas', label: 'SAS', monaco: 'sas', prism: 'sas' },
  { value: 'shell', label: 'Shell Script', monaco: 'shell', prism: 'shell' },
  { value: 'smali', label: 'Smali', monaco: 'smali', prism: 'smali' },
  { value: 'st', label: 'Structured Text', monaco: 'st', prism: 'st' },
  { value: 'stata', label: 'Stata', monaco: 'stata', prism: 'stata' },
  { value: 'step21', label: 'STEP21', monaco: 'step21', prism: 'step21' },
  { value: 'subunit', label: 'Subunit', monaco: 'subunit', prism: 'subunit' },
  { value: 'turtle', label: 'Turtle', monaco: 'turtle', prism: 'turtle' },
  { value: 'velocity', label: 'Velocity', monaco: 'velocity', prism: 'velocity' },
  { value: 'x86asm', label: 'x86 Assembly', monaco: 'x86asm', prism: 'x86asm' },
  { value: 'xquery', label: 'XQuery', monaco: 'xquery', prism: 'xquery' },
  { value: 'yacas', label: 'Yacas', monaco: 'yacas', prism: 'yacas' },
  { value: 'zephir', label: 'Zephir', monaco: 'zephir', prism: 'zephir' },
  // 数据科学和机器学习相关
  { value: 'jupyter', label: 'Jupyter Notebook', monaco: 'jupyter', prism: 'json' },
  { value: 'pandas', label: 'Pandas', monaco: 'python', prism: 'python' },
  { value: 'numpy', label: 'NumPy', monaco: 'python', prism: 'python' },
  { value: 'tensorflow', label: 'TensorFlow', monaco: 'python', prism: 'python' },
  { value: 'pytorch', label: 'PyTorch', monaco: 'python', prism: 'python' },
  { value: 'keras', label: 'Keras', monaco: 'python', prism: 'python' },
  { value: 'scikit-learn', label: 'Scikit-learn', monaco: 'python', prism: 'python' },
  { value: 'plotly', label: 'Plotly', monaco: 'python', prism: 'python' },
  { value: 'matplotlib', label: 'Matplotlib', monaco: 'python', prism: 'python' },
  { value: 'seaborn', label: 'Seaborn', monaco: 'python', prism: 'python' },
  { value: 'opencv', label: 'OpenCV', monaco: 'python', prism: 'python' },
  { value: 'nltk', label: 'NLTK', monaco: 'python', prism: 'python' },
  { value: 'spacy', label: 'spaCy', monaco: 'python', prism: 'python' },
  { value: 'transformers', label: 'Transformers', monaco: 'python', prism: 'python' },
  { value: 'pyspark', label: 'PySpark', monaco: 'python', prism: 'python' },
  { value: 'dask', label: 'Dask', monaco: 'python', prism: 'python' },
  { value: 'polars', label: 'Polars', monaco: 'rust', prism: 'rust' },
  { value: 'arrow', label: 'Apache Arrow', monaco: 'rust', prism: 'rust' },
  { value: 'vaex', label: 'Vaex', monaco: 'python', prism: 'python' },
  { value: 'databricks', label: 'Databricks', monaco: 'sql', prism: 'sql' },
  { value: 'snowflake', label: 'Snowflake SQL', monaco: 'sql', prism: 'sql' },
  { value: 'redshift', label: 'Amazon Redshift', monaco: 'sql', prism: 'sql' },
  { value: 'bigquery', label: 'Google BigQuery', monaco: 'sql', prism: 'sql' },
  // 区块链和智能合约
  { value: 'vyper', label: 'Vyper', monaco: 'python', prism: 'python' },
  { value: 'yul', label: 'Yul', monaco: 'yul', prism: 'yul' },
  { value: 'move', label: 'Move', monaco: 'move', prism: 'move' },
  { value: 'ink', label: 'Ink!', monaco: 'rust', prism: 'rust' },
  // Web 框架和工具
  { value: 'nextjs', label: 'Next.js', monaco: 'javascript', prism: 'javascript' },
  { value: 'nuxt', label: 'Nuxt.js', monaco: 'javascript', prism: 'javascript' },
  { value: 'sapper', label: 'Sapper', monaco: 'javascript', prism: 'javascript' },
  { value: 'gatsby', label: 'Gatsby', monaco: 'javascript', prism: 'javascript' },
  { value: 'remix', label: 'Remix', monaco: 'typescript', prism: 'typescript' },
  { value: 'astro', label: 'Astro', monaco: 'astro', prism: 'astro' },
  { value: 'sveltekit', label: 'SvelteKit', monaco: 'javascript', prism: 'javascript' },
  // 配置和部署
  { value: 'terraform', label: 'Terraform', monaco: 'hcl', prism: 'hcl' },
  { value: 'ansible', label: 'Ansible', monaco: 'yaml', prism: 'yaml' },
  { value: 'k8s', label: 'Kubernetes YAML', monaco: 'yaml', prism: 'yaml' },
  { value: 'docker-compose', label: 'Docker Compose', monaco: 'yaml', prism: 'yaml' },
  { value: 'helm', label: 'Helm Chart', monaco: 'yaml', prism: 'yaml' },
  { value: 'pulumi', label: 'Pulumi', monaco: 'typescript', prism: 'typescript' },
  { value: 'serverless', label: 'Serverless Framework', monaco: 'yaml', prism: 'yaml' },
  { value: 'vagrant', label: 'Vagrant', monaco: 'ruby', prism: 'ruby' },
  { value: 'packer', label: 'Packer', monaco: 'json', prism: 'json' },
  // 游戏开发
  { value: 'gdscript', label: 'GDScript', monaco: 'python', prism: 'python' },
  { value: 'hlsl', label: 'HLSL', monaco: 'hlsl', prism: 'hlsl' },
  { value: 'glsl', label: 'GLSL', monaco: 'glsl', prism: 'glsl' },
  { value: 'unity-csharp', label: 'Unity C#', monaco: 'csharp', prism: 'csharp' },
  { value: 'unreal-blueprint', label: 'Unreal Blueprint', monaco: 'javascript', prism: 'javascript' },
  { value: 'ampl', label: 'AMPL', monaco: 'ampl', prism: 'ampl' },
  // 函数式编程语言
  { value: 'elm', label: 'Elm', monaco: 'elm', prism: 'elm' },
  { value: 'elixir', label: 'Elixir', monaco: 'elixir', prism: 'elixir' },
  { value: 'erlang', label: 'Erlang', monaco: 'erlang', prism: 'erlang' },
  { value: 'idris', label: 'Idris', monaco: 'idris', prism: 'idris' },
  { value: 'agda', label: 'Agda', monaco: 'agda', prism: 'agda' },
  { value: 'coq', label: 'Coq', monaco: 'coq', prism: 'coq' },
  { value: 'fstar', label: 'F*', monaco: 'fstar', prism: 'fstar' },
  { value: 'lean', label: 'Lean', monaco: 'lean', prism: 'lean' },
  // 领域特定语言 (DSL)
  { value: 'graphql', label: 'GraphQL', monaco: 'graphql', prism: 'graphql' },
  { value: 'gql', label: 'GraphQL Schema', monaco: 'graphql', prism: 'graphql' },
  { value: 'relay', label: 'Relay', monaco: 'javascript', prism: 'javascript' },
  { value: 'apollo', label: 'Apollo', monaco: 'typescript', prism: 'typescript' },
  { value: 'prisma', label: 'Prisma Schema', monaco: 'prisma', prism: 'prisma' },
  { value: 'drizzle', label: 'Drizzle ORM', monaco: 'typescript', prism: 'typescript' },
  { value: 'typeorm', label: 'TypeORM', monaco: 'typescript', prism: 'typescript' },
  { value: 'sequelize', label: 'Sequelize', monaco: 'javascript', prism: 'javascript' },
  { value: 'mongoose', label: 'Mongoose', monaco: 'javascript', prism: 'javascript' },
  { value: 'prisma-client', label: 'Prisma Client', monaco: 'typescript', prism: 'typescript' },
  { value: 'hasura', label: 'Hasura Metadata', monaco: 'yaml', prism: 'yaml' },
  { value: 'supabase', label: 'Supabase Config', monaco: 'typescript', prism: 'typescript' },
  { value: 'firebase', label: 'Firebase Rules', monaco: 'javascript', prism: 'javascript' },
  { value: 'appwrite', label: 'Appwrite Functions', monaco: 'javascript', prism: 'javascript' },
  { value: 'convex', label: 'Convex Functions', monaco: 'typescript', prism: 'typescript' },
  { value: 'supabase-edge', label: 'Supabase Edge Functions', monaco: 'typescript', prism: 'typescript' },
  { value: 'vercel-ai', label: 'Vercel AI SDK', monaco: 'typescript', prism: 'typescript' },
  { value: 'langchain', label: 'LangChain', monaco: 'python', prism: 'python' },
  { value: 'llamaindex', label: 'LlamaIndex', monaco: 'python', prism: 'python' },
  { value: 'crewai', label: 'CrewAI', monaco: 'python', prism: 'python' },
  { value: 'autogen', label: 'AutoGen', monaco: 'python', prism: 'python' },
  { value: 'haystack', label: 'Haystack', monaco: 'python', prism: 'python' },
  { value: 'semantic-kernel', label: 'Semantic Kernel', monaco: 'csharp', prism: 'csharp' },
  { value: 'guidance', label: 'Guidance', monaco: 'python', prism: 'python' },
  { value: 'outlines', label: 'Outlines', monaco: 'python', prism: 'python' },
  { value: 'llama.cpp', label: 'llama.cpp', monaco: 'cpp', prism: 'cpp' },
  { value: 'onnx', label: 'ONNX', monaco: 'protobuf', prism: 'protobuf' },
  { value: 'tensorrt', label: 'TensorRT', monaco: 'cpp', prism: 'cpp' },
  { value: 'coreml', label: 'Core ML', monaco: 'protobuf', prism: 'protobuf' },
  { value: 'tflite', label: 'TensorFlow Lite', monaco: 'c', prism: 'c' },
  { value: 'onnxruntime', label: 'ONNX Runtime', monaco: 'cpp', prism: 'cpp' },
  // 云原生和微服务
  { value: 'istio', label: 'Istio Config', monaco: 'yaml', prism: 'yaml' },
  { value: 'linkerd', label: 'Linkerd Config', monaco: 'yaml', prism: 'yaml' },
  { value: 'consul', label: 'Consul Config', monaco: 'hcl', prism: 'hcl' },
  { value: 'vault', label: 'Vault Policies', monaco: 'hcl', prism: 'hcl' },
  { value: 'nomad', label: 'Nomad Job', monaco: 'hcl', prism: 'hcl' },
  { value: 'packer', label: 'Packer Template', monaco: 'json', prism: 'json' },
  { value: 'vagrant', label: 'Vagrantfile', monaco: 'ruby', prism: 'ruby' },
  { value: 'dockerfile-multi', label: 'Multi-stage Dockerfile', monaco: 'dockerfile', prism: 'dockerfile' },
  { value: 'buildkit', label: 'BuildKit', monaco: 'dockerfile', prism: 'dockerfile' },
  { value: 'buildah', label: 'Buildah Script', monaco: 'bash', prism: 'bash' },
  { value: 'kaniko', label: 'Kaniko Config', monaco: 'yaml', prism: 'yaml' },
  { value: 'skopeo', label: 'Skopeo Config', monaco: 'yaml', prism: 'yaml' },
  // 边缘计算和 IoT
  { value: 'wasm-module', label: 'WASM Module', monaco: 'wasm', prism: 'wast' },
  { value: 'wasi', label: 'WASI', monaco: 'c', prism: 'c' },
  { value: 'assemblyscript', label: 'AssemblyScript', monaco: 'typescript', prism: 'typescript' },
  { value: 'grain', label: 'Grain', monaco: 'grain', prism: 'grain' },
  { value: 'zig', label: 'Zig', monaco: 'zig', prism: 'zig' },
  { value: 'odin', label: 'Odin', monaco: 'odin', prism: 'odin' },
  { value: 'jai', label: 'Jai', monaco: 'c', prism: 'c' },
  { value: 'carbon', label: 'Carbon', monaco: 'carbon', prism: 'carbon' },
  { value: 'vala', label: 'Vala', monaco: 'vala', prism: 'vala' },
  { value: 'genie', label: 'Genie', monaco: 'genie', prism: 'genie' },
  { value: 'pike', label: 'Pike', monaco: 'pike', prism: 'pike' },
  { value: 'chuck', label: 'ChucK', monaco: 'chuck', prism: 'chuck' },
  { value: 'supercollider', label: 'SuperCollider', monaco: 'supercollider', prism: 'supercollider' },
  { value: 'tidal', label: 'TidalCycles', monaco: 'haskell', prism: 'haskell' },
  { value: 'foxdot', label: 'FoxDot', monaco: 'python', prism: 'python' },
  { value: 'sonicpi', label: 'Sonic Pi', monaco: 'ruby', prism: 'ruby' },
  { value: 'overtone', label: 'Overtone', monaco: 'clojure', prism: 'clojure' },
  // 量子计算
  { value: 'qiskit', label: 'Qiskit', monaco: 'python', prism: 'python' },
  { value: 'cirq', label: 'Cirq', monaco: 'python', prism: 'python' },
  { value: 'qsharp', label: 'Q#', monaco: 'qsharp', prism: 'qsharp' },
  { value: 'quipper', label: 'Quipper', monaco: 'haskell', prism: 'haskell' },
  { value: 'projectq', label: 'ProjectQ', monaco: 'python', prism: 'python' },
  { value: 'forest', label: 'Forest (pyQuil)', monaco: 'python', prism: 'python' },
  { value: 'openqasm', label: 'OpenQASM', monaco: 'qasm', prism: 'qasm' },
  { value: 'strawberry', label: 'Strawberry Fields', monaco: 'python', prism: 'python' },
  { value: 'pennylane', label: 'PennyLane', monaco: 'python', prism: 'python' },
  // 生物信息学和计算生物学
  { value: 'biopython', label: 'BioPython', monaco: 'python', prism: 'python' },
  { value: 'bioconductor', label: 'Bioconductor', monaco: 'r', prism: 'r' },
  { value: 'bedtools', label: 'BEDTools', monaco: 'bash', prism: 'bash' },
  { value: 'samtools', label: 'SAMTools', monaco: 'bash', prism: 'bash' },
  { value: 'gatk', label: 'GATK', monaco: 'java', prism: 'java' },
  { value: 'plink', label: 'PLINK', monaco: 'bash', prism: 'bash' },
  { value: 'vcf', label: 'VCF Format', monaco: 'text', prism: 'text' },
  { value: 'fasta', label: 'FASTA', monaco: 'text', prism: 'text' },
  { value: 'fastq', label: 'FASTQ', monaco: 'text', prism: 'text' },
  { value: 'sam', label: 'SAM Format', monaco: 'text', prism: 'text' },
  { value: 'bam', label: 'BAM Format', monaco: 'text', prism: 'text' },
  { value: 'bed', label: 'BED Format', monaco: 'text', prism: 'text' },
  { value: 'gff', label: 'GFF Format', monaco: 'text', prism: 'text' },
  { value: 'gtf', label: 'GTF Format', monaco: 'text', prism: 'text' },
  // 金融技术
  { value: 'mql4', label: 'MQL4', monaco: 'cpp', prism: 'cpp' },
  { value: 'mql5', label: 'MQL5', monaco: 'cpp', prism: 'cpp' },
  { value: 'thinkscript', label: 'ThinkScript', monaco: 'thinkscript', prism: 'thinkscript' },
  { value: 'pine-script', label: 'Pine Script', monaco: 'javascript', prism: 'javascript' },
  { value: 'tradingview', label: 'TradingView', monaco: 'javascript', prism: 'javascript' },
  { value: 'metatrader', label: 'MetaTrader', monaco: 'cpp', prism: 'cpp' },
  { value: 'multicharts', label: 'MultiCharts', monaco: 'pascal', prism: 'pascal' },
  { value: 'ninjatrader', label: 'NinjaTrader', monaco: 'csharp', prism: 'csharp' },
  { value: 'tradelink', label: 'TradeLink', monaco: 'csharp', prism: 'csharp' },
  { value: 'quantlib', label: 'QuantLib', monaco: 'cpp', prism: 'cpp' },
  { value: 'zipline', label: 'Zipline', monaco: 'python', prism: 'python' },
  { value: 'backtrader', label: 'Backtrader', monaco: 'python', prism: 'python' },
  { value: 'pyalgotrade', label: 'PyAlgoTrade', monaco: 'python', prism: 'python' },
  { value: 'vnpy', label: 'VN.py', monaco: 'python', prism: 'python' },
  { value: 'freqtrade', label: 'Freqtrade', monaco: 'python', prism: 'python' },
  { value: 'ccxt', label: 'CCXT', monaco: 'javascript', prism: 'javascript' },
  { value: 'hummingbot', label: 'Hummingbot', monaco: 'python', prism: 'python' },
  { value: 'freqtrade', label: 'Freqtrade Strategy', monaco: 'python', prism: 'python' },
];

export const getLanguageByValue = (value: string) => {
  return languageOptions.find(lang => lang.value === value) || 
         languageOptions.find(lang => lang.value === 'text')!;
};

export const getMonacoLanguage = (value: string) => {
  return getLanguageByValue(value).monaco;
};

export const getPrismLanguage = (value: string) => {
  return getLanguageByValue(value).prism;
};

/**
 * Map a language value (lowercase key like "javascript") to the CSS
 * class used by the `.lang-<key> .lang-badge-dot` rules in globals.css.
 * Unknown languages get no dot class (the dot defaults to muted).
 */
export function getLanguageBadgeClass(value: string): string {
  const known: Record<string, string> = {
    javascript: 'lang-javascript',
    jsx: 'lang-javascript',
    tsx: 'lang-typescript',
    typescript: 'lang-typescript',
    python: 'lang-python',
    ruby: 'lang-ruby',
    java: 'lang-java',
    go: 'lang-go',
    rust: 'lang-rust',
    c: 'lang-c',
    cpp: 'lang-cpp',
    csharp: 'lang-cpp',
    php: 'lang-php',
    html: 'lang-html',
    css: 'lang-css',
    scss: 'lang-css',
    less: 'lang-css',
    json: 'lang-json',
    markdown: 'lang-markdown',
    bash: 'lang-bash',
    shell: 'lang-shell',
    sql: 'lang-sql',
    yaml: 'lang-yaml',
    dockerfile: 'lang-dockerfile',
    xml: 'lang-xml',
    toml: 'lang-toml',
    diff: 'lang-diff',
    vue: 'lang-vue',
    svelte: 'lang-svelte',
    swift: 'lang-swift',
    kotlin: 'lang-kotlin',
    scala: 'lang-scala',
    perl: 'lang-perl',
    r: 'lang-r',
    dart: 'lang-dart',
    lua: 'lang-lua',
    graphql: 'lang-graphql',
    yul: 'lang-yul',
  };
  return known[value] || '';
}

/**
 * Human-readable label for a language value.
 */
export function getLanguageLabel(value: string): string {
  return getLanguageByValue(value).label;
}